site_name: my grasp of harmony
site_description: An understandable initiation to musical harmony
site_author: Guillaume Cerutti

nav:
    - 'Home': 'index.md'
    - 'Introduction': 'introduction.md'

theme:
    name: material
    logo: "assets/images/logo.svg"
    palette:
        primary: custom
    font:
        text: Outfit
    icon:
        admonition:
            note: fontawesome/solid/music

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

plugins:
    - mkdocs-audiotag:
        preload: metadata   # none | metadata | auto
        loop: false
        controls: true
        autoplay: false
        muted: false
        width: 100%
    - mkdocs-wavesurfer:
        height: 64
        cursor_width: 1
        bar_width: 4
        bar_gap: 1
        normalize: true
        auto_scroll: true

extra_css:
    - assets/css/style.css